--- 
avatar: /images/logo.png
baseurl: ""
description: "Autorizat ANRE"
disqus: smblog-4us
exclude: 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
footer-links: 
  creator: "http://sm-design.ro"
  dribbble: ~
  email: cosmin.iuresel@home-electric.ro
  facebook: HomeElectricCDI
  flickr: ~
  github: ~
  googleplus: u/0/b/102876120754765239538/+Home-electricRo
  instagram: ~
  linkedin: ~
  pinterest: ~
  rss: ~
  stackoverflow: ~
  twitter: ~
  youtube: ~
gems: 
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-timeago
google_analytics: UA-61875005-1
jekyll_timeago: 
  and: și
  day: zi
  days: zile
  month: lună
  months: luni
  prefix: ""
  prefix_future: ""
  suffix: "în urmă"
  suffix_future: in
  today: azi
  tomorrow: mâine
  week: sătpămână
  weeks: săptămâni
  year: an
  years: ani
  yesterday: ieri
kramdown: 
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    css_class: highlight
name: "Home Electric"
permalink: "/:year/:month/:day/:title/"
sass: 
  style: !ruby/symbol expanded
url: soulmatters.github.io/home-electric
version: v1.2.0
